default_install_hook_types: [pre-commit, pre-push]
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--unsafe]
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.43.0
    hooks:
      - id: markdownlint
        args: [--fix, --disable, MD013, MD033, MD041, MD024, --]
  - repo: local
    hooks:
      - id: pytest-registry
        name: pytest-registry (fast)
        entry: pytest
        language: system
        pass_filenames: false
        args: ["test/test_registry.py", "-x", "--tb=short"]
        always_run: true
        verbose: true
  - repo: local
    hooks:
      - id: pytest
        name: pytest (full)
        entry: pytest
        language: system
        pass_filenames: false
        args: ["test", "-x", "--tb=short"]
        stages: [pre-push]
        always_run: true
        verbose: true
  - repo: local
    hooks:
      - id: pytest-benchmark
        name: pytest-benchmark
        entry: pytest
        language: system
        pass_filenames: false
        args: ["benchmark", "-x", "--tb=short", "-sv"]
        stages: [pre-push]
        always_run: true
        verbose: true
